name: autobolt
channels:
  - conda-forge
dependencies:
  - python=3.10
  - fenics  # ⚠️ FEniCS (classic version) works ONLY on Linux and WSL — not native Windows
  - meshio  # Used for mesh I/O (convert .msh <-> .xdmf/.xml)
  - numpy
  - scipy
  - matplotlib
  - pip
  - pip:
      - gmsh # gmsh Python API — available via pip for Windows and Linux
      - build123d
      - pyyaml